# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=52, null=True, verbose_name='Name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('amount', models.CharField(max_length=12)),
                ('transaction_id', models.CharField(blank=True, max_length=126, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('AED', 'AED'), ('SGD', 'SGD')], default='USD', max_length=15)),
            ],
        ),
    ]
